fluent/fluentd-ui

app/assets/stylesheets/common.css.scss
app/controllers/fluentd/settings/histories_controller.rb
app/controllers/fluentd/settings/notes_controller.rb
app/controllers/fluentd/settings/running_backup_controller.rb
app/controllers/fluentd/settings_controller.rb
app/models/concerns/fluentd/setting_archive/archivable.rb
app/models/fluentd/agent/local_common.rb
app/models/fluentd/setting_archive/backup_file.rb
app/models/fluentd/setting_archive/note.rb
app/views/fluentd/settings/histories/_list.html.haml
app/views/fluentd/settings/histories/show.html.haml
config/locales/translation_en.yml
config/locales/translation_ja.yml
config/routes.rb
spec/features/fluentd/setting/hisotries_spec.rb
spec/features/fluentd/setting/notes_spec.rb
spec/features/setting_spec.rb

This PR enables to add a note with each configuration histories.
See the following screen capture.

Enable to add a note with each configuration histories

---

app/models/fluentd/setting/out_s3.rb

fluent-plugin-s3 removes `s3_endpoint` config parameter.
https://github.com/fluent/fluent-plugin-s3/blob/master/ChangeLog

Follow out_s3 plugin ver 0.5.x

---

app/models/fluent_gem.rb

when no data exists.
it causes the following error.
``` 
TypeError (no _dump_data is defined for class Enumerator):
app/models/fluent_gem.rb:19:in `list'
app/models/plugin.rb:89:in `block in installed'
app/models/plugin.rb:88:in `installed'
app/controllers/plugins_controller.rb:7:in `installed'
```

Fix to avoid pass Enumerator to Rails.cache.fetch

---

app/assets/javascripts/vue/in_tail_format.js

Previewing regexp is using Ajax fired by input field changed.
if server-side processing is slow and/or client-side input so fast, multiple Ajax are running.
That causes #145 issue.
This PR fix to avoid multiple requesting at the same time.

Fix flashing regexp (Fix #145)

---

app/models/fluent_gem.rb
lib/fluentd-ui.rb
spec/models/fluentd/agent/local_common_spec.rb
spec/spec_helper.rb

Fix unstable spec on circle ci

---

app/models/fluentd/setting/out_s3.rb

Remove `add_newline`, `output_tag` and `output_time` from s3 setting then I don't get any warnings with out_s3 0.5.6.
@repeatedly Now, generated config as below. looks good?
```
<match s3.**>
type s3
aws_key_id XXXXXXXXXXXXX
aws_sec_key XXXXXXXX
s3_bucket bbb
s3_region us-west-1
format out_file
include_time_key false
store_as gzip
use_ssl true
buffer_type memory
</match>
```

Fix #157 remove parameters causing warn on fluentd

---

app/models/fluentd/setting/out_mongo.rb
app/models/fluentd/setting/out_s3.rb
app/models/fluentd/setting/out_td.rb

Display error message if `buffer_type` choice `file` and `buffer_path` is blank on configuration flow.

Fix #158 validation for buffer_path when buffer_type is 'file'

---

app/helpers/settings_helper.rb

String-interpolation is broken in `append_and_remove_links()`.
Plus/Minus icons are displayed like: `icon('fa-plus')}`, not the Plus/Minus signs.
This affects for URL path: daemon/setting/out_forward.

fix broken string-interpolation in append_and_remove_links()

---

app/views/sessions/new.html.haml

I apply "form-control" class to inputbox in login page.
Before:
After:

Apply bootstrap inputbox design to ones in login form

---

app/controllers/fluentd/settings_controller.rb
spec/features/setting_spec.rb

```
<source>
type forward
id "foo#{Time.now.to_s}"
</source>
```
like this config, configtest was passed, but Update & Restart was failed.
This PR fixes that behavior (should be success).

Fix configtest/update behaviors are mismatched

---

Gemfile
Gemfile.lock
spec/models/fluentd/agent/common_spec.rb
spec/spec_helper.rb

I found rspec `its` syntax is used in few specs, so I revised them without `its`. After I removed this gem from dependencies.

Remove rspec-its gem

---

lib/fluentd-ui/command.rb

refs #176 
I added `--host` option to `start` command.
The `rackup` command runs in the back of `start` command binds `localhost` as default on https://github.com/rack/rack/pull/514 . This option enables to change this.
**edited**: I changed default host to `0.0.0.0` from `localhost` for backward compatibility.
```
$ ./bin/fluentd-ui start
Puma 2.11.1 starting...
* Min threads: 0, max threads: 16
* Environment: production
* Listening on tcp://0.0.0.0:9292
```
```
$ ./bin/fluentd-ui start --host localhost
Puma 2.11.1 starting...
* Min threads: 0, max threads: 16
* Environment: production
* Listening on tcp://localhost:9292
```

Add `--host` option

---

app/controllers/users_controller.rb
app/models/user.rb
spec/features/sessions_spec.rb
spec/features/users_spec.rb
spec/models/user_spec.rb

Now, password can be changed unexpectedly even if password doesn't match password\_confirmation. I fixed this bug and add specs.
The spec for `User#valid?` with invalid password\_confirmation exists before, but this spec passed by other validations ( `current_user is wrong` and `password is too short`).

Fix changing password without confirmation

---

lib/tasks/release.rake

This task updated Changelog, version.rb, and Gemfile.lock.
1. Detect merged PR number.
2. Make new version (revision bump up)
3. Add new Changelog template(PR number and its URL) to `Changelog`.
4. Bump up version in `lib/fluentd-ui/version.rb`
5. `bundle install` to update `Gemfile.lock`

Add task to prepare releasing

---

app/views/fluentd/settings/in_tail/_form.html.haml

Align box and label for checkbox

---

app/views/shared/vue/_in_tail_format.html.erb

Mouse pointer changes `pointer` face on `<label>`, but nothing occured when it was clicked. I added `for` attributes to `<label>`, `id` to `<input>` or `<select>` so they get focus when its label is clicked.

Focus inputbox when its label is clicked

---

app/controllers/fluentd/settings_controller.rb

`Fluentd::Settings` module also exists, so sometime solving namespace failed (e.g. fluentd-ui server shut down still dashboard page is opened, so server restart and "Config file" menu in its page is clicked, raise error.)

Clarify namespace even under Fluentd namespace

---

app/views/fluentd/settings/source_and_output.html.haml

Before: (the icon is clickable, but i didn't look it so...)
After:

Apply button style to the dom to refresh current setting source and output

---

circle.yml

I want to use Ruby > 2.1.3 (matched with `td-agent2`), but CIrcleCI uses ruby 1.9.3 as default.
In additon, I want to use the latest `td-agent` in CircleCI.

Use ruby2.1.3 in CircleCI (for v0.4.0)

---

README.md

I missed this change in the previous PR :bow:

Specify ruby version in README

---

ChangeLog
ChangeLog.md
lib/tasks/release.rake

If changelog uses markdown, GitHub view is comfortable (easy to read, link available)
edited: I should to modify `lib/tasks/release.rake` (`rake release:prepare` task)

Use markdown to changelog

---

fluentd-ui.gemspec

We use Apache license for fluentd-ui.

Fix mismatching LICENSE between LICENSE and gemspec

---

lib/regexp_preview/single_line.rb

Fluentd raises an exception for raw Hash in newer versions.

Use Config::Element instead of raw Hash

---

config/application.yml

Hi. Boundio has shutdown and migrated to Twilio for now.
https://www.facebook.com/TwilioforKWC/posts/524150507622893

boundio service migrated to twilio

---

config/application.yml

Because Growl does not work with OS X 10.10 or later.

Growl migrated terminal-notifier

---

spec/controllers/polling_controller_spec.rb

> DEPRECATION WARNING: The success? predicate is deprecated and will
> be removed in Rails 6.0. Please use successful? as provided by
> Rack::Response::Helpers.
Signed-off-by: Kenji Okimoto <okimoto@clear-code.com>

Suppress deprecation warning

---

README.md
app/javascript/packs/aws_credential.js
app/javascript/packs/in_tail_parse.js
app/javascript/packs/owned_plugin_form.js
app/javascript/packs/settings.js
app/javascript/packs/transport_config.js
app/javascript/packs/transport_section.js
app/javascript/packs/treeview.js
app/views/layouts/application.html.erb
config.ru

Support relative path

---

app/models/plugin.rb
app/views/plugins/recommended.html.haml
app/views/plugins/updated.html.haml
config/application.yml
config/locales/translation_en.yml
config/locales/translation_ja.yml

Remove following plugins
* fluent-plugin-secure-forward
* fluent-plugin-forest
* fluent-plugin-scribe
* fluent-plugin-parser
* fluent-plugin-file-alternative
* fluent-plugin-zabbix-simple-buffered
* fluent-plugin-grep
* fluent-plugin-kestrel

Update recommended plugins

---

app/models/concerns/fluentd/setting/configurable.rb
app/models/concerns/fluentd/setting/label.rb

Because the label is not an argument.

Set label properly

---

Gemfile.lock

See https://nvd.nist.gov/vuln/detail/CVE-2018-16468

Update loofah to 2.2.3

---

app/models/concerns/fluentd/setting/plugin.rb

In such case, use value set by super class.
Close #277

Stop overwriting parameter type by `nil`

---

.travis.yml

Because mini_portile2 requires bundler ~> 1.17
Signed-off-by: Takuro Ashie <ashie@clear-code.com>

travis: Use bundler-1.17

---

package.json
yarn.lock

Otherwise bootstrap isn't installed on a certain environment.
Signed-off-by: Takuro Ashie <ashie@clear-code.com>

Add missing dependency: bootstrap

---

yarn.lock

$ yarn upgrade @rails/webpacker
node-sass ^4.11.0 has a security vulnerability, so
it should be 4.13.1 or later, but node-sass was hold by
@rails/webpacker, so webpacker should be upgraded first.

Fix node-sass related vulnerability

---

test/models/fluentd/setting/in_forward_test.rb

It fixes the following test
```
Failure: test: .initial_params(Fluentd::Setting::InForwardTest)
/work/fluentd/fluentdui/fluentd-ui/test/models/fluentd/setting/in_forward_test.rb:62:in `block in <class:InForwardTest>'
59:           }
60:         },
61:       }
=> 62:       assert_equal(expected, @klass.initial_params)
63:     end
64:
65:     test "#valid?" do
<{:backlog=>nil,
```

Fix test failure by missing expected parameters

---

Gemfile
Gemfile.lock

It is required to support recent Ruby.
NOTE:
* Ruby 2.6: Webmock 3.5.0 or later
* Ruby 2.7: Webmock 3.8.0 or later
Ruby 2.4 support was dropped since Webmock 3.9.0

Use latest webmock

---

.travis.yml

As Ruby 2.4 had already reached EOL
TODO: migrate Travis CI to GitHub Actions as a next step

Drop Ruby 2.4 support

---

yarn.lock

datatables.net 1.10.19 is vulnerable version, but it was hold by
datatables.net-bs4 1.10.19.
startbootstrap-sb-admin should be upgraded because datatables.net-bs4
was hold by it.
$ yarn upgrade startbootstrap-sb-admin

Upgrade datatables.net

---

package.json
yarn.lock

$ yarn upgrade datatables.net-bs4@1.10.24
The vulnerable version of datatables.net 1.10.19 is not used anymore.
(datatables.net-bs4 depends on datatables.net 1.10.19)

Upgrade to datatables.net-bs4

---

README.md

This PR updates two outdated/broken links in the README as reported in [\#457](https://github.com/fluent/fluentd-ui/issues/457):
- **td-agent:**
The previous link to td-agent is now obsolete, as td-agent reached End of Life in Dec 2023. The new link points to the [Fluent Package download page](https://www.fluentd.org/download/fluent_package), which is the official migration path for td-agent users and provides LTS releases and migration guidance.
- **ChromeDriver:**
The previous ChromeDriver download link was no longer accessible. It is now replaced with the official [ChromeDriver downloads page](https://chromedriver.chromium.org/downloads), which is current and maintained.
- In the introduction, updated the td-agent link to:
`[td-agent](https://www.fluentd.org/download/fluent_package)`
- …

Fix: Update broken links for td-agent (EOL) and ChromeDriver in README 
