fluent/fluentd-ui

app/helpers/settings_helper.rb

- Breaks method up for clarity and readability

Changes in response to CodeClimate score for settings_helper.rb

---

app/views/fluentd/settings/histories/_list.html.haml

Puts th inside thead, puts tr in tbody

---

app/controllers/polling_controller.rb
spec/controllers/polling_controller_spec.rb

After verifying tests passed, also addressed duplicated code reported by code climate.

Adds tests to polling controller

---

app/views/plugins/updated.html.haml

Another small fix to html structure

Puts th inside thead, puts tr in tbody (plugins#updated)

---

app/helpers/settings_helper.rb
spec/features/fluentd/setting/out_forward_spec.rb

Fix this: https://github.com/fluent/fluentd-ui/pull/126/files#r22839905

Fix SettingHelper for hidden field

---

app/controllers/fluentd/agents_controller.rb
app/models/plugin.rb
spec/controllers/fluentd/agents_controller_spec.rb

Avoid duplication: plugin model, fluentd/agents_controller
Added tests: fluentd/agents_controller_spec

Responds to code climate

---

app/controllers/application_controller.rb
app/helpers/miscs_helper.rb
app/views/layouts/application.html.erb
db/seeds.rb
spec/controllers/application_controller_spec.rb

Cosme and trivial refactors

---

app/models/fluentd/agent/fluentd_gem.rb
app/models/fluentd/agent/local_common.rb
app/models/fluentd/agent/td_agent/macosx.rb
app/models/fluentd/agent/td_agent/unix.rb
spec/models/fluentd/agent_spec.rb

Adding `dryrun` method to agents for checking config file is valid or not.

Check with dryrun

---

app/controllers/misc_controller.rb
spec/controllers/misc_controller_spec.rb
spec/controllers/plugins_controller_spec.rb
spec/controllers/tutorials_controller_spec.rb

Refactor #download_info of MiscController

---

app/models/fluentd/agent/local_common.rb
lib/file_reverse_reader.rb
spec/support/fixtures/error3.log
spec/support/fluentd_agent_common_behavior.rb

Before, it put serial other error log into one error subject and it's notes.
Fix to divide them into each error subject.

Fix logged error

---

README.md

Found a typo in the README file.

Changed TO to To

---

README.md

fluentd -> Fluentd (when appearing as the project's name)
pidfile -> pid file

made minor stylistic changes

---

app/controllers/fluentd/settings_controller.rb
app/models/fluentd/agent.rb
app/models/fluentd/agent/common.rb
app/models/fluentd/agent/fluentd_gem.rb
app/models/fluentd/agent/local_common.rb
app/models/fluentd/agent/td_agent.rb
app/models/fluentd/agent/td_agent/macosx.rb
app/models/fluentd/agent/td_agent/unix.rb
app/views/fluentd/settings/edit.html.haml
circle.yml
spec/models/fluentd/agent_spec.rb
spec/spec_helper.rb
spec/support/fluentd_agent_common_behavior.rb

Adding configtest button into setting#edit page.

Dryrun button to config edit

---

app/controllers/fluentd/settings_controller.rb
app/models/fluentd/agent/fluentd_gem.rb
app/models/fluentd/agent/local_common.rb
app/models/fluentd/agent/td_agent.rb
spec/models/plugin_spec.rb

Code climate

---

fluentd-ui.gemspec

Need this patch for td-agent 2.2.0.

Relax fluentd version

---

app/models/fluentd/agent/fluentd_gem.rb

Prevent zombie processes from increasing

---

lib/tasks/release.rake

Fix a typo in filename

---

app/views/shared/vue/_in_tail_format.html.erb

Align in tails after file choosed

---

app/assets/stylesheets/common.css.scss
app/views/shared/vue/_fluent_log.html.erb

- Use `form-control` and `form-inline` class (from bootstrap)
- Use `div` tag and class to add margin in the bottom of log operation section.
Before:
After:

Tweak dashboard inputbox

---

app/assets/javascripts/vue/in_tail_format.js
app/controllers/api_controller.rb
app/models/fluentd/setting/in_tail.rb
app/views/fluentd/settings/in_tail/after_file_choose.html.haml
app/views/shared/vue/_in_tail_format.html.erb
config/application.yml
config/locales/translation_en.yml
config/locales/translation_ja.yml
lib/regexp_preview.rb
lib/regexp_preview/multi_line.rb
lib/regexp_preview/single_line.rb
spec/lib/regexp_preview/multi_line_spec.rb
spec/lib/regexp_preview/single_line_spec.rb
spec/support/fixtures/error4.log

support multiline for In tail

---

Gemfile.lock
fluentd-ui.gemspec

Update httpclient to follow td-agent dependency.

Fix #193 update httpclient

---

README.md

https://github.com/fluent/fluentd-docs/pull/175
Export some texts to docs.fluentd.org

Simplify README, rely on docs.fluentd.org for detail

---

fluentd-ui.gemspec

See https://spdx.org/licenses/
Signed-off-by: Kenji Okimoto <okimoto@clear-code.com>

Fix license identifier

---

app/controllers/api/config_definitions_controller.rb
app/form_builders/fluentd_form_builder.rb
app/javascript/packs/config_field.js
app/javascript/packs/out_forward_setting.js
app/javascript/packs/owned_plugin_form.js
app/javascript/packs/transport_config.js
app/javascript/packs/transport_section.js
app/models/concerns/fluentd/setting/configurable.rb
app/models/concerns/fluentd/setting/plugin_config.rb
app/models/concerns/fluentd/setting/plugin_parameter.rb
app/models/concerns/fluentd/setting/section_validator.rb
app/models/fluentd/setting/in_forward.rb
app/models/fluentd/setting/in_syslog.rb
app/models/fluentd/setting/out_forward.rb
app/views/fluentd/settings/in_forward/_form.html.haml
app/views/fluentd/settings/out_forward/_form.html.haml
app/views/shared/settings/show.html.haml
app/views/shared/vue/_config_field.html.haml
app/views/shared/vue/_out_forward_setting.html.haml
app/views/shared/vue/_transport_config.html.haml
app/views/shared/vue/_transport_section.html.haml

This is for in_forward, out_forward.
We don't support in_syslog's transport section, for now.

Support transport section

---

.travis.yml
gemfiles/ruby2.2.gemfile

Capybara 3.3 does not support Ruby 2.2

Add gemfile for Ruby2.2

---

.travis.yml

Install gem/npm packages properly.

Make runnable CI

---

app/assets/stylesheets/common.css.scss
app/controllers/fluentd_controller.rb
app/models/fluentd.rb
app/views/fluentd/_form.html.haml
app/views/fluentd/show.html.haml
app/views/layouts/application.html.erb
config/locales/translation_en.yml
config/locales/translation_ja.yml

Add note to Fluentd model

---

app/javascript/packs/application.js
app/javascript/packs/config_field.js
app/javascript/packs/in_tail_parse.js
app/javascript/packs/owned_plugin_form.js
app/javascript/packs/parser_plugin_form.js
app/javascript/packs/plugin_setting.js
app/javascript/packs/store/index.js
app/javascript/packs/store/modules/parser_params.js
app/models/concerns/fluentd/setting/formatter_advanced_options.rb
app/models/concerns/fluentd/setting/parser_advanced_options.rb
app/models/concerns/fluentd/setting/plugin.rb
app/models/fluentd/setting/buffer_file.rb
app/models/fluentd/setting/buffer_memory.rb
app/models/fluentd/setting/parser_ltsv.rb
app/models/fluentd/setting/parser_regexp.rb
app/models/fluentd/setting/parser_syslog.rb
app/views/shared/settings/_form.html.haml
app/views/shared/vue/_config_field.html.haml
app/views/shared/vue/_in_tail_parse.html.haml
app/views/shared/vue/_owned_plugin_form.html.haml
app/views/shared/vue/_parser_plugin_form.html.haml
lib/regexp_preview/multi_line.rb
lib/regexp_preview/single_line.rb
package.json
yarn.lock

introduce vuex to manage the data for parser parameters

Fix preview functionality in in_tail wizard

---

ChangeLog.md
Gemfile.lock
lib/fluentd-ui/version.rb

Signed-off-by: Kenji Okimoto <okimoto@clear-code.com>

Prepare to release v1.2.0

---

README.md

Especially description about `yarn` seems missing.

README.md: Add missing installation procedures

---

Gemfile
Gemfile.lock
test/test_helper.rb

Because chromedriver-helper is deprecated.

Use webdrivers instead of chromedriver-helper

---

config/locales/translation_en.yml
config/locales/translation_ja.yml

Signed-off-by: Takuro Ashie <ashie@clear-code.com>

Fix broken links to document pages
